version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

